
version: '3.4'

services:
  nathan_DevBatch_gateway:
    image: inductiveautomation/ignition:latest
    ports:
      - "12088:8088"
      - "12043:8043"
      - "12060:8060"
    
    # env_file: ignition.env  # optionally specify variables in a file, or using `environment:` below
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=admin
      - GATEWAY_ADMIN_PASSWORD=admin
      - IGNITION_EDITION=full
      #- IGNITION_LICENSE_KEY =
      #- IGNITION_ACTIVATION_TOKEN = 
      - TZ=America/New_York

    command: 
      -n nathan-batch-dev-gateway 
      -a 127.0.0.1 
      -h 12088 
      -s 12043
      
   
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - nathan_DevBatch_data:/usr/local/bin/ignition/data
  
     
  
  nathan_ignitionDev_db:
    image: mariadb:latest
    ports:
     - "3312:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=ignition
      - MYSQL_DATABASE=ignition
      
    volumes:
      - nathan_ignitionDevBatch_db:/var/lib/mysql


  adminer_container:
        image: adminer:latest
        environment: 
            ADMINER_DEFAULT_SERVER: nathan_ignitionDev_db
            ADMINER_DESIGN: dracula # galkaev
        ports: 
          - 12080:8080


volumes: 
  nathan_DevBatch_data:  
  nathan_ignitionDevBatch_db: 
